### ISSUE TITLE
Building on Fedora 34: multiple definition of `opuscodec'

### ISSUE THREAD

**Issue by kdknigga** [christf/snapcastc#68]
Hello,

I'm trying to build on Fedora 34 (cmake version 3.20.5, gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1), GNU ld version 2.35.2-6.fc34) and I'm getting a lot of messages about "multiple definition of `opuscodec'" and then the build fails.

```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):                                                                                                                                                                       
  Compatibility with CMake < 2.8.12 will be removed from a future version of                                                                                                                                                                  
  CMake.                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                              
  Update the VERSION argument <min> value or use a ...<max> suffix to tell                                                                                                                                                                    
  CMake that the project does not need compatibility with older versions.
                                                           
                                                                                                                                                                                                                                              
-- The C compiler identification is GNU 11.2.1                                                                                                                                                                                                
-- Detecting C compiler ABI info                                                                                                                                                                                                              
-- Detecting C compiler ABI info - done                                                                                                                                                                                                       
-- Check for working C compiler: /usr/bin/cc - skipped                                                                                                                                                                                        
-- Detecting C compile features                                                                                                                                                                                                               
-- Detecting C compile features - done                                                                                                                                                                                                        
-- Found ALSA: /usr/lib64/libasound.so (found version "1.2.5.1")                                                                                                                                                                              
-- Configuring done                                                                                                                                                                                                                           
-- Generating done                                                                                                                                                                                                                            
-- Build files have been written to: /home/kris/git/snapcastc/build                                                                                                                                                                           
[ 20%] Building C object src/CMakeFiles/common_libs.dir/util.c.o                                                                                                                                                                              
[ 20%] Building C object src/CMakeFiles/server_deps.dir/clientmgr.c.o                                                                                                                                                                         
[ 20%] Building C object src/CMakeFiles/client_deps.dir/alsaplayer.c.o                                                                                                                                                                        
[ 20%] Building C object src/CMakeFiles/client_deps.dir/intercom_client.c.o                                                                                                                                                                   
[ 20%] Building C object src/CMakeFiles/server_deps.dir/intercom_srv.c.o                                                                                                                                                                      
[ 24%] Building C object src/CMakeFiles/common_libs.dir/taskqueue.c.o                                                                                                                                                                         
[ 28%] Building C object src/CMakeFiles/server_deps.dir/inputpipe.c.o                                                                                                                                                                         
[ 32%] Building C object src/CMakeFiles/client_deps.dir/pqueue.c.o                                                                                                                                                                            
[ 36%] Building C object src/CMakeFiles/common_libs.dir/timespec.c.o                                                                                                                                                                          
[ 40%] Building C object src/CMakeFiles/common_libs.dir/vector.c.o
[ 40%] Built target client_deps                                                                                        
[ 44%] Building C object src/CMakeFiles/common_libs.dir/syscallwrappers.c.o                 
[ 48%] Building C object src/CMakeFiles/common_libs.dir/intercom.c.o
[ 52%] Building C object src/CMakeFiles/server_deps.dir/socket.c.o                                                     
[ 56%] Building C object src/CMakeFiles/common_libs.dir/pcmchunk.c.o                         
[ 60%] Building C object src/CMakeFiles/common_libs.dir/opuscodec.c.o                  
[ 64%] Building C object src/CMakeFiles/server_deps.dir/jsonrpc.c.o
[ 68%] Building C object src/CMakeFiles/server_deps.dir/stream.c.o
[ 68%] Built target common_libs
[ 76%] Building C object src/CMakeFiles/snapcast-test-client.dir/client-test.c.o
[ 76%] Building C object src/CMakeFiles/snapcast-client.dir/client.c.o
[ 76%] Built target server_deps
[ 84%] Building C object src/CMakeFiles/snapcast-server.dir/server.c.o
[ 84%] Building C object src/CMakeFiles/snapcast-test-srv.dir/server-test.c.o
[ 88%] Linking C executable snapcast-test-client
[ 92%] Linking C executable snapcast-client
/usr/bin/ld: CMakeFiles/client_deps.dir/intercom_client.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-client.dir/client-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/client_deps.dir/alsaplayer.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-client.dir/client-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/util.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-client.dir/client-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/taskqueue.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-client.dir/client-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/intercom.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-client.dir/client-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/pcmchunk.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-client.dir/client-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/opuscodec.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-client.dir/client-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/client_deps.dir/intercom_client.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-client.dir/client.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/client_deps.dir/alsaplayer.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-client.dir/client.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/util.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-client.dir/client.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/taskqueue.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-client.dir/client.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/intercom.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-client.dir/client.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/pcmchunk.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-client.dir/client.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/opuscodec.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-client.dir/client.c.o:(.bss+0x0): first defined here
[ 96%] Linking C executable snapcast-test-srv
[100%] Linking C executable snapcast-server
/usr/bin/ld: CMakeFiles/server_deps.dir/intercom_srv.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-srv.dir/server-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/server_deps.dir/clientmgr.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-srv.dir/server-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/server_deps.dir/inputpipe.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-srv.dir/server-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/server_deps.dir/socket.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-srv.dir/server-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/server_deps.dir/stream.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-srv.dir/server-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/util.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-srv.dir/server-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/taskqueue.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-srv.dir/server-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/intercom.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-srv.dir/server-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/pcmchunk.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-srv.dir/server-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/opuscodec.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-srv.dir/server-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/server_deps.dir/intercom_srv.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-server.dir/server.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/server_deps.dir/clientmgr.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-server.dir/server.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/server_deps.dir/inputpipe.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-server.dir/server.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/server_deps.dir/socket.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-server.dir/server.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/server_deps.dir/stream.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-server.dir/server.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/util.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-server.dir/server.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/taskqueue.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-server.dir/server.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/intercom.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-server.dir/server.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/pcmchunk.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-server.dir/server.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/opuscodec.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-server.dir/server.c.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/snapcast-test-client.dir/build.make:121: src/snapcast-test-client] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: src/CMakeFiles/snapcast-test-client.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/snapcast-client.dir/build.make:121: src/snapcast-client] Error 1
make[1]: *** [CMakeFiles/Makefile2:244: src/CMakeFiles/snapcast-client.dir/all] Error 2
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/snapcast-test-srv.dir/build.make:127: src/snapcast-test-srv] Error 1
make[1]: *** [CMakeFiles/Makefile2:138: src/CMakeFiles/snapcast-test-srv.dir/all] Error 2
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/snapcast-server.dir/build.make:127: src/snapcast-server] Error 1
make[1]: *** [CMakeFiles/Makefile2:165: src/CMakeFiles/snapcast-server.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Consolidate compiler generated dependencies of target common_libs
[ 32%] Built target common_libs
Consolidate compiler generated dependencies of target client_deps
[ 44%] Built target client_deps
Consolidate compiler generated dependencies of target snapcast-test-client
[ 48%] Linking C executable snapcast-test-client
/usr/bin/ld: CMakeFiles/client_deps.dir/intercom_client.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-client.dir/client-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/client_deps.dir/alsaplayer.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-client.dir/client-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/util.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-client.dir/client-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/taskqueue.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-client.dir/client-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/intercom.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-client.dir/client-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/pcmchunk.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-client.dir/client-test.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/common_libs.dir/opuscodec.c.o:(.bss+0x0): multiple definition of `opuscodec'; CMakeFiles/snapcast-test-client.dir/client-test.c.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/snapcast-test-client.dir/build.make:121: src/snapcast-test-client] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: src/CMakeFiles/snapcast-test-client.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

Any ideas what could be the problem?
